### ISSUE TITLE
how to show the results

### ISSUE THREAD

**Issue by zhangyujia0223** [nnUyi/Non-Local-Nets#7]
I have trained the minist, and want to check the result and architecture. As I input the following command:
![image](https://user-images.githubusercontent.com/28782048/38005854-97ed5554-327d-11e8-8d4e-07d07a3684be.png)
![image](https://user-images.githubusercontent.com/28782048/38005891-c83efe7e-327d-11e8-9ea5-3dfa52beece2.png)
could you give me some guidance?

**Comment by feynman233** [comment]
I think just ‘tensorboard --logdir=logs/minst’ is ok  @zhangyujia0223
